version: '2.3'
services:

  website:
    image: website
    build:
      context: .
    container_name: website
    hostname: website
    mem_limit: 1024m
    restart: always
    ports:
      - 5000:5000
    healthcheck:
      test: ps aux | grep "flask run" | grep -v grep || exit 1
      interval: 20s
      timeout: 10s
      retries: 5